### ISSUE TITLE
Official  name of this project?

### ISSUE THREAD

**Issue by YihaoSu** [Astrohackers-TW/IANCUPyData#2]
Any idea about the official name of this project and the directory name for downloaded data?

**Comment by chengchungchen** [comment]
M...........How about "Head First Python for Astronomy/Astronomer" XD

**Comment by pschiang** [comment]
downloaded data ==> data or demo_data  
project name ==> come up nothing yet... Orz

**Comment by YihaoSu** [comment]
iancupy_data   XD
